project:
  type: website
  resources:
    - stats140cv.pdf
    - stats101cpdf.df
    - ro53pdf.pdf
    - math150pdf.pdf

website:
  title: "Chinmay's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: experience.qmd
        text: Experience

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



